name: NextJS

on:
  push:
    branches: '*'
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
      - name: Install Dependencies
        run: npm install
      - name: Build NextJS
        run: npm run build
